### ISSUE TITLE
Where to get SNP report

### ISSUE THREAD

**Issue by shuk777** [LIT-Protocol/sev-snp-utils#1]

**Comment by shuk777** [comment]
Hi, there
I'm new to SEV SNP attestation. I'm kind of confused about how to get SNP attestation report from within the guest VM(seems that you already take the attestation as a file)

**Comment by glitch003** [comment]
Hey, this repo is mainly for working with Lit Protocol stuff.  This is probably not the right place for this kind of question.  We don't work for AMD and are just other users of SEV-SNP like you.  

Just curious though, what are you working on @shuk777 ?  SEV-SNP is super cool and pretty new so not many people are working with it yet.

I think this repo might have better info on how to get the attestation report: https://github.com/AMDESE/sev-guest

**Comment by rhomber** [comment]
FYI we just released the crate 'sev-snp-utils' and updated the docs to show how to request a report.

Still interested to hear what you're working on though :)
